SELECT D.Dnumber, D.Dname
FROM DEPARTMENT D
EXCEPT
SELECT DISTINCT D.Dnumber, D.Dname
FROM WORKS_ON W LEFT JOIN PROJECT P ON W.Pno = P.Pnumber
	RIGHT JOIN EMPLOYEE E ON W.Essn = E.Ssn
	LEFT JOIN DEPARTMENT D ON E.Dno = D.Dnumber
WHERE P.Pname = 'ProductX'
ORDER BY D.Dnumber ASC